spring:
  application:
    name: Project

  session:
    store-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/xhh?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: Mysql
    show-sql: true
    generate-ddl: false

#Freemark 配置#
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html                   #后缀名
    settings:
      number_format: '0.##'             #数字格式化，无小数点
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

server:
  port: 5000  #Tomcat端口
  max-http-header-size: 4194304
  tomcat:
    max-http-post-size: 0

#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://101.200.63.82:5003/eureka/  #Eureka Server

  #服务注册时，在Eureka的实例配置
  #metadata-map.cluster：指定服务集群名称（一个服务集群包括多个app）
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    metadata-map:
      cluster: MAIN

#自定义参数
appConfig:
  appName: myDecorate
  appNameCn: 高起装饰公司

  secretOfCoreService: secretOfCoreService_dev    #核心服务调用密钥