spring:
  application:
    name: Project

  session:
    store-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/xhh?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: Mysql
    show-sql: true
    generate-ddl: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
