spring:
  application:
    name: Project

  session:
    store-type: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xhh?characterEncoding=UTF-8
    username: root
    password:
#    url: jdbc:mysql://101.200.63.82:3306/xhh?characterEncoding=UTF-8
#    username: admin
#    password: XmIhnJh15215.@#4$
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: Mysql
    show-sql: true
    generate-ddl: false
#Freemark 配置#
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html                   #后缀名
    settings:
      number_format: '0.##'             #数字格式化，无小数点

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

server:
  port: 80  #Tomcat端口
  max-http-header-size: 4194304
  tomcat:
    max-http-post-size: 0